#version de sintaxis
version: "3.9"

#definir servicios
services:
  proyectos-backend-micro:
    container_name: proyectos-backend-micro
    image: proyectos-backend-micro:v1
    build:
      context: .
    ports:
      - "4001"
    networks:
      - proyectos-app

  proyectos-backend-micro-2:
    container_name: proyectos-backend-micro-2
    image: proyectos-backend-micro:v1
    ports:
      - "4001"
    networks:
      - proyectos-app

  balanceador-carga:
    container_name: balanceador-carga
    image: balanceador-carga:v1
    build:
      context: ./balanceador
    ports:
      - 4004:80
    networks:
      - proyectos-app

networks:
  proyectos-app: